@baseUrl = http://localhost:3000
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjcsImlhdCI6MTc2Njg0NTUxOSwiZXhwIjoxNzY3MTA0NzE5fQ.9-zqSNh3dO2_mcXcQODqGKMhlPQHtslBsc9LnIdjukY
@taskId = 12

### [1] 할 일에 댓글 추가
# @name createComment
POST {{baseUrl}}/tasks/{{taskId}}/comments
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "content": "이 업무 오늘까지 마무리 가능한가요???ㅎㅎ"
}

### 생성된 댓글 ID 저장
@commentId = {{createComment.response.body.id}}


### [2] 할 일에 달린 댓글 조회
GET {{baseUrl}}/tasks/{{taskId}}/comments
Authorization: Bearer {{accessToken}}


# ### 할 일에 달린 댓글 조회 (1페이지, 5개씩)
# GET {{baseUrl}}/tasks/{{taskId}}/comments?page=1&limit=5
# Authorization: Bearer {{accessToken}}

### [3] 댓글 수정
PATCH {{baseUrl}}/comments/{{commentId}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "content": "내용을 수정했습니다. 내일까지 부탁드려요!"
}


### [4] 댓글 삭제
DELETE {{baseUrl}}/comments/{{commentId}}
Authorization: Bearer {{accessToken}}