@baseUrl = http://localhost:3000

# 1. 소유자(Owner)의 토큰을 여기에 넣으세요
@ownerToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjYsImlhdCI6MTc2NjgzOTUxOSwiZXhwIjoxNzY3MDk4NzE5fQ.0oOW3tXYKeYMKJTQD8mXHbKnaacCgurjMMbPhPfx_UM

# 2. 초대받을 사람(Friend)의 토큰을 여기에 넣으세요
@inviteeToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjcsImlhdCI6MTc2Njg0NTUxOSwiZXhwIjoxNzY3MTA0NzE5fQ.9-zqSNh3dO2_mcXcQODqGKMhlPQHtslBsc9LnIdjukY

# 테스트할 프로젝트 ID
@projectId = 5

### [1] 멤버 초대 보내기 (소유자가 실행)
# @name sendInvite
POST {{baseUrl}}/projects/{{projectId}}/invitations
Content-Type: application/json
Authorization: Bearer {{ownerToken}}

{
  "email": "commentMember1@example.com"
}

### 생성된 초대 ID 저장 (UUID)
@invitationId = {{sendInvite.response.body.invitationId}}


### [2] 프로젝트 멤버 목록 조회 (현재 상태 확인)
GET {{baseUrl}}/projects/{{projectId}}/users?page=1&limit=10
Authorization: Bearer {{ownerToken}}


### [3] 멤버 초대 수락 (초대받은 사람이 실행)
# 주의: Authorization 헤더에 inviteeToken을 사용해야 합니다!
POST {{baseUrl}}/invitations/{{invitationId}}/accept
Authorization: Bearer {{inviteeToken}}


### [4] 멤버 초대 삭제/취소 (소유자가 수락 전에 실행하거나 관리용)
# 수락하기 전에 이 요청을 보내면 초대장이 사라집니다.
DELETE {{baseUrl}}/invitations/{{invitationId}}
Authorization: Bearer {{ownerToken}}


### [5] 프로젝트에서 멤버 제외하기 (강퇴)
# 친구가 수락한 후에, 친구의 유저 ID(예: 2)를 넣어 실행합니다.
@targetUserId = 2
DELETE {{baseUrl}}/projects/{{projectId}}/users/{{targetUserId}}
Authorization: Bearer {{ownerToken}}